name: todo_list
description: Todo List with Provider and SQLITE.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.3
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_overlay_loader: ^2.0.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3
  synchronized: ^3.1.0+1
  validatorless: ^1.2.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf
