// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVJa4xG_Ojq8E47PsDyiHvdtaCiIAbx0w',
    appId: '1:521452060607:android:ebe5b8f1b9702b41a9eb0a',
    messagingSenderId: '521452060607',
    projectId: 'todo-list-d2467',
    storageBucket: 'todo-list-d2467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJY2nwFqxzrB8Mdw7Tli7kGtfgfDq_xzI',
    appId: '1:521452060607:ios:01d50ff84ef1cfaba9eb0a',
    messagingSenderId: '521452060607',
    projectId: 'todo-list-d2467',
    storageBucket: 'todo-list-d2467.appspot.com',
    androidClientId: '521452060607-p8abgf34c2lb21vc4rig8apgi43q3qmg.apps.googleusercontent.com',
    iosClientId: '521452060607-4a33cd6q3qhvhmdebbbqh74pc5qq9sge.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
